#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=16
#PBS -N tables_diversity
#PBS -A d411-training
#PBS -j oe

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/tables_diversity/
cd ~/output/tables_diversity/

time core_diversity_analyses.py \
-i ~/output/pickOTU_joined/otus/otu_table.biom \
-m ~/mapping_file_team8.tsv \
-t ~/output/pickOTU_joined/otus/97_otus.tree \
-o ./output \
-e 34000 \
-a -O 16 \
--recover_from_failure

echo "closing environment"
conda deactivate

