#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=8
#PBS -N permanova
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/permanova/
cd ~/output/permanova/

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Rind_or_Core \
-o permanova_core \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Store \
-o permanova_store \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Store_Type \
-o permanova_storetype \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Raw_or_Pasteurised \
-o permanova_raw \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Soft_or_Hard \
-o permanova_soft \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Region \
-o permanova_region \

time compare_categories.py \
--method permanova \
-i ~/output/tables_diversity/output/bdiv_even34000/unweighted_unifrac_dm.txt \
-m ~/mapping_file_team8.tsv \
-c Country \
-o permanova_country \

conda deactivate


